package com.ked.interaction.enums;

public enum EConversationStep {
    BOT_MESSAGE_TEXT_INPUT,
    BOT_MESSAGE_BUTTON_ADD_CHOICE,
    BOT_MESSAGE_BUTTON_INPUT,
    BOT_MESSAGE_SEND_CHOICE,
    BOT_MESSAGE_TYPE_CHOICE,

    TRANSACTION_TYPE_CHOICE,
    TRANSACTION_CATEGORY_CHOICE,
    TRANSACTION_INPUT,
}
