package com.ked.interaction.enums;

public enum EConversationStep {
    BOT_MESSAGE_TEXT_INPUT,
    BOT_MESSAGE_BUTTON_ADD_CHOICE,
    BOT_MESSAGE_BUTTON_INPUT,
    BOT_MESSAGE_SEND_CHOICE,
    BOT_MESSAGE_TYPE_CHOICE,

    TRANSACTION_TYPE_CHOICE,
    TRANSACTION_CATEGORY_CHOICE,
    TRANSACTION_INPUT,

    CONFIGURE_CHOICE,

    CONFIGURE_CATEGORY_ACTION_CHOICE,
    CATEGORY_NAME_INPUT,
    CATEGORY_TYPE_CHOICE,
    CATEGORY_CHOICE,
    CATEGORY_NEW_NAME_INPUT,

    CHANGE_USERNAME_INPUT,

    STATISTIC_PERIOD_CHOICE,
    STATISTIC_LAST_DATE_INPUT,
}
